// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0TEh6HkVnjgkcHUeOemdQBRre20w_j1E',
    appId: '1:96798704386:web:98b64993533f267e6ef81b',
    messagingSenderId: '96798704386',
    projectId: 'labview2-21425',
    authDomain: 'labview2-21425.firebaseapp.com',
    databaseURL: 'https://labview2-21425-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'labview2-21425.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS3lw3dQaCAc04P3GHM6h1vBYfWQBUNfg',
    appId: '1:96798704386:android:2ad3f84155aa45036ef81b',
    messagingSenderId: '96798704386',
    projectId: 'labview2-21425',
    databaseURL: 'https://labview2-21425-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'labview2-21425.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAO8YaxA-FjR_jpLhxsJX9ZZ9bRuAEXPQ0',
    appId: '1:96798704386:ios:09cfa2a4c8200edb6ef81b',
    messagingSenderId: '96798704386',
    projectId: 'labview2-21425',
    databaseURL: 'https://labview2-21425-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'labview2-21425.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationCloudLed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAO8YaxA-FjR_jpLhxsJX9ZZ9bRuAEXPQ0',
    appId: '1:96798704386:ios:09cfa2a4c8200edb6ef81b',
    messagingSenderId: '96798704386',
    projectId: 'labview2-21425',
    databaseURL: 'https://labview2-21425-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'labview2-21425.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationCloudLed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0TEh6HkVnjgkcHUeOemdQBRre20w_j1E',
    appId: '1:96798704386:web:8806feaf648618d26ef81b',
    messagingSenderId: '96798704386',
    projectId: 'labview2-21425',
    authDomain: 'labview2-21425.firebaseapp.com',
    databaseURL: 'https://labview2-21425-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'labview2-21425.firebasestorage.app',
  );
}
